import Vue from 'vue'
import Vuex from 'vuex'

Vue.use(Vuex)

export default new Vuex.Store({
  state: {
    "africa": {
      "members": {
        "Angola": 0,
        "Benin": 92,
        "Botswana": 108,
        "Burkina Faso": 0,
        "Burundi": 35,
        "Capo Verde": 0,
        "Cameroon": 269,
        "Central African Republic": 0,
        "Chad": 0,
        "Comoros": 0,
        "Republic of the Congo": 45,
        "Ivory Coast": 43,
        "Democratic Republic of the Congo": 31,
        "Equatorial Guinea": 0,
        "Eritrea": 0,
        "eSwatini": 0,
        "Ethiopia": 78,
        "Gabon": 0,
        "The Gambia": 0,
        "Ghana": 330,
        "Guinea": 0,
        "Guinea-Bissau": 0,
        "Kenya": 418,
        "Lesotho": 26,
        "Liberia": 0,
        "Madagascar": 30,
        "Malawi": 64,
        "Mali": 0,
        "Mauritania": 0,
        "Mauritius": 50,
        "Mozambique": 79,
        "Namibia": 35,
        "Niger": 25,
        "Nigeria": 1987,
        "Rwanda": 131,
        "São Tomé and Príncipe": 0,
        "Senegal": 47,
        "Seychelles": 0,
        "Sierra Leone": 0,
        "Somalia": 0,
        "South Africa": 495,
        "Tanzania": 173,
        "Togo": 0,
        "Uganda": 98,
        "Western Sahara": 0,
        "Zambia": 74,
        "Zimbabwe": 331
      },
      "ongoing_phd_fellows": {
        "Angola": 0,
        "Benin": 7,
        "Botswana": 0,
        "Burkina Faso": 1,
        "Burundi": 2,
        "Capo Verde": 0,
        "Cameroon": 18,
        "Central African Republic": 0,
        "Chad": 0,
        "Comoros": 0,
        "Republic of the Congo": 1,
        "Ivory Coast": 0,
        "Democratic Republic of the Congo": 1,
        "Equatorial Guinea": 0,
        "Eritrea": 0,
        "eSwatini": 2,
        "Ethiopia": 7,
        "Gabon": 0,
        "The Gambia": 0,
        "Ghana": 3,
        "Guinea": 0,
        "Guinea-Bissau": 0,
        "Kenya": 6,
        "Lesotho": 2,
        "Liberia": 0,
        "Madagascar": 2,
        "Malawi": 0,
        "Mali": 0,
        "Mauritania": 1,
        "Mauritius": 0,
        "Mozambique": 6,
        "Namibia": 0,
        "Niger": 0,
        "Nigeria": 0,
        "Rwanda": 6,
        "São Tomé and Príncipe": 0,
        "Senegal": 3,
        "Seychelles": 0,
        "Sierra Leone": 0,
        "Somalia": 0,
        "South Africa": 0,
        "Tanzania": 5,
        "Togo": 0,
        "Uganda": 7,
        "Western Sahara": 0,
        "Zambia": 2,
        "Zimbabwe": 10
      },
      "alumni": {
        "Angola": 1,
        "Benin": 12,
        "Botswana": 3,
        "Burkina Faso": 2,
        "Burundi": 0,
        "Capo Verde": 0,
        "Cameroon": 40,
        "Central African Republic": 0,
        "Chad": 0,
        "Comoros": 0,
        "Republic of the Congo": 3,
        "Ivory Coast": 0,
        "Democratic Republic of the Congo": 7,
        "Equatorial Guinea": 0,
        "Eritrea": 0,
        "eSwatini": 2,
        "Ethiopia": 19,
        "Gabon": 2,
        "The Gambia": 1,
        "Ghana": 18,
        "Guinea": 0,
        "Guinea-Bissau": 0,
        "Kenya": 33,
        "Lesotho": 4,
        "Liberia": 0,
        "Madagascar": 5,
        "Malawi": 6,
        "Mali": 0,
        "Mauritania": 3,
        "Mauritius": 1,
        "Mozambique": 4,
        "Namibia": 3,
        "Niger": 0,
        "Nigeria": 75,
        "Rwanda": 9,
        "São Tomé and Príncipe": 0,
        "Senegal": 3,
        "Seychelles": 0,
        "Sierra Leone": 1,
        "Somalia": 0,
        "South Africa": 2,
        "Tanzania": 12,
        "Togo": 3,
        "Uganda": 16,
        "Western Sahara": 0,
        "Zambia": 6,
        "Zimbabwe": 23
      }
    },
    "sudamerica": {
      "members": {
        "Angola": 0,
        "Benin": 92,
        "Botswana": 108,
        "Burkina Faso": 0,
        "Burundi": 35,
        "Capo Verde": 0,
        "Cameroon": 269,
        "Central African Republic": 0,
        "Chad": 0,
        "Comoros": 0,
        "Republic of the Congo": 45,
        "Ivory Coast": 43,
        "Democratic Republic of the Congo": 31,
        "Equatorial Guinea": 0,
        "Eritrea": 0,
        "eSwatini": 0,
        "Ethiopia": 78,
        "Gabon": 0,
        "The Gambia": 0,
        "Ghana": 330,
        "Guinea": 0,
        "Guinea-Bissau": 0,
        "Kenya": 418,
        "Lesotho": 26,
        "Liberia": 0,
        "Madagascar": 30,
        "Malawi": 64,
        "Mali": 0,
        "Mauritania": 0,
        "Mauritius": 50,
        "Mozambique": 79,
        "Namibia": 35,
        "Niger": 25,
        "Nigeria": 1987,
        "Rwanda": 131,
        "São Tomé and Príncipe": 0,
        "Senegal": 47,
        "Seychelles": 0,
        "Sierra Leone": 0,
        "Somalia": 0,
        "South Africa": 495,
        "Tanzania": 173,
        "Togo": 0,
        "Uganda": 98,
        "Western Sahara": 0,
        "Zambia": 74,
        "Zimbabwe": 331
      },
      "ongoing_phd_fellows": {
        "Angola": 0,
        "Benin": 7,
        "Botswana": 0,
        "Burkina Faso": 1,
        "Burundi": 2,
        "Capo Verde": 0,
        "Cameroon": 18,
        "Central African Republic": 0,
        "Chad": 0,
        "Comoros": 0,
        "Republic of the Congo": 1,
        "Ivory Coast": 0,
        "Democratic Republic of the Congo": 1,
        "Equatorial Guinea": 0,
        "Eritrea": 0,
        "eSwatini": 2,
        "Ethiopia": 7,
        "Gabon": 0,
        "The Gambia": 0,
        "Ghana": 3,
        "Guinea": 0,
        "Guinea-Bissau": 0,
        "Kenya": 6,
        "Lesotho": 2,
        "Liberia": 0,
        "Madagascar": 2,
        "Malawi": 0,
        "Mali": 0,
        "Mauritania": 1,
        "Mauritius": 0,
        "Mozambique": 6,
        "Namibia": 0,
        "Niger": 0,
        "Nigeria": 0,
        "Rwanda": 6,
        "São Tomé and Príncipe": 0,
        "Senegal": 3,
        "Seychelles": 0,
        "Sierra Leone": 0,
        "Somalia": 0,
        "South Africa": 0,
        "Tanzania": 5,
        "Togo": 0,
        "Uganda": 7,
        "Western Sahara": 0,
        "Zambia": 2,
        "Zimbabwe": 10
      },
      "alumni": {
        "Angola": 1,
        "Benin": 12,
        "Botswana": 3,
        "Burkina Faso": 2,
        "Burundi": 0,
        "Capo Verde": 0,
        "Cameroon": 40,
        "Central African Republic": 0,
        "Chad": 0,
        "Comoros": 0,
        "Republic of the Congo": 3,
        "Ivory Coast": 0,
        "Democratic Republic of the Congo": 7,
        "Equatorial Guinea": 0,
        "Eritrea": 0,
        "eSwatini": 2,
        "Ethiopia": 19,
        "Gabon": 2,
        "The Gambia": 1,
        "Ghana": 18,
        "Guinea": 0,
        "Guinea-Bissau": 0,
        "Kenya": 33,
        "Lesotho": 4,
        "Liberia": 0,
        "Madagascar": 5,
        "Malawi": 6,
        "Mali": 0,
        "Mauritania": 3,
        "Mauritius": 1,
        "Mozambique": 4,
        "Namibia": 3,
        "Niger": 0,
        "Nigeria": 75,
        "Rwanda": 9,
        "São Tomé and Príncipe": 0,
        "Senegal": 3,
        "Seychelles": 0,
        "Sierra Leone": 1,
        "Somalia": 0,
        "South Africa": 2,
        "Tanzania": 12,
        "Togo": 3,
        "Uganda": 16,
        "Western Sahara": 0,
        "Zambia": 6,
        "Zimbabwe": 23
      }
    }
  },
  getters: {
    getAfrica: state => {
      return state.africa.members
    },
    getPhdAfrica: state => {
      return state.africa.ongoing_phd_fellows
    },
    getAlumniAfrica: state => {
      return state.africa.alumni
    },
    getSudAmerica: state => {
      return state.sudamerica.members
    },
    getPhdSudAmerica: state => {
      return state.sudamerica.ongoing_phd_fellows
    },
    getAlumniSudAmerica: state => {
      return state.africa.alumni
    },
  },
  mutations: {
  },
  actions: {
  },
  modules: {
  }
})
